### ISSUE TITLE
Add Change Thumbnail option

### ISSUE THREAD

**Issue by andriusmv** [br4adam/bookmarks#1]
# ✨ Add 'Change Thumbnail' option
For those bookmarks that don't have a default thumbnail or those with ugly default-thumbnails.

**Comment by br4adam** [comment]
Added the option to change thumbnail image.

![thumbnail](https://github.com/br4adam/bookmarks/assets/104263751/5f2026c2-066b-4db4-9ac1-d55b888691cb)
